// SPDX-License-Identifier: Apache-2.0
// Licensed to the Ed-Fi Alliance under one or more agreements.
// The Ed-Fi Alliance licenses this file to you under the Apache License, Version 2.0.
// See the LICENSE and NOTICES files in the project root for more information.

using System.Collections.Generic;
using System.Linq;
using EdFi.Ods.Common.Conventions;
using EdFi.Ods.Common.Models.Domain;

namespace EdFi.Ods.Common.Models.Definitions.Transformers;

/// <summary>
/// Implements a transformer that removes the PriorDescriptorId property from the edfi.Descriptor entity's definition
/// to prevent any artifacts from being generated or rendered for it. This class should be removed once the property
/// has been removed from the source ApiModel.json file generated by MetaEd.
/// </summary>
public class PriorDescriptorIdRemover : IDomainModelDefinitionsTransformer
{
    public IEnumerable<DomainModelDefinitions> TransformDefinitions(IEnumerable<DomainModelDefinitions> definitions)
    {
        foreach (DomainModelDefinitions domainModelDefinitions in definitions)
        {
            // Look for the edfi.Descriptor entity definition
            var entityDefinition = domainModelDefinitions.EntityDefinitions.FirstOrDefault(
                ed => new FullName(ed.Schema, ed.Name) == EdFiConventions.DescriptorFullName);

            if (entityDefinition != null)
            {
                // Remove the PriorDescriptorId property
                entityDefinition.LocallyDefinedProperties =
                    entityDefinition.LocallyDefinedProperties
                        .Where(p => p.PropertyName != "PriorDescriptorId")
                        .ToArray();
            }

            yield return domainModelDefinitions;
        }
    }
}
