-- SPDX-License-Identifier: Apache-2.0
-- Licensed to the Ed-Fi Alliance under one or more agreements.
-- The Ed-Fi Alliance licenses this file to you under the Apache License, Version 2.0.
-- See the LICENSE and NOTICES files in the project root for more information.

/*
Deployment script for EdFi_Ods_Empty_Template_Target

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
PRINT N'Dropping [auth].[EducationOrganizationToStaffUSI_Assignment].[UCIX_EducationOrganizationToStaffUSI_Assignment]...';


GO
DROP INDEX [UCIX_EducationOrganizationToStaffUSI_Assignment]
    ON [auth].[EducationOrganizationToStaffUSI_Assignment];


GO
PRINT N'Dropping [auth].[EducationOrganizationToStaffUSI_Employment].[UCIX_EducationOrganizationToStaffUSI_Employment]...';


GO
DROP INDEX [UCIX_EducationOrganizationToStaffUSI_Employment]
    ON [auth].[EducationOrganizationToStaffUSI_Employment];


GO
PRINT N'Dropping [auth].[LocalEducationAgencyIdToParentUSI].[UCIX_LocalEducationAgencyIdToParentUSI]...';


GO
DROP INDEX [UCIX_LocalEducationAgencyIdToParentUSI]
    ON [auth].[LocalEducationAgencyIdToParentUSI];


GO
PRINT N'Dropping [auth].[LocalEducationAgencyIdToStudentUSI].[UCIX_LocalEducationAgencyToStudentUSI]...';


GO
DROP INDEX [UCIX_LocalEducationAgencyToStudentUSI]
    ON [auth].[LocalEducationAgencyIdToStudentUSI];


GO
PRINT N'Dropping [auth].[ParentUSIToSchoolId].[UCIX_ParentUSIToSchoolId]...';


GO
DROP INDEX [UCIX_ParentUSIToSchoolId]
    ON [auth].[ParentUSIToSchoolId];


GO
PRINT N'Dropping [auth].[ParentUSIToStudentUSI].[IX_ParentUSIToStudentUSI]...';


GO
DROP INDEX [IX_ParentUSIToStudentUSI]
    ON [auth].[ParentUSIToStudentUSI];


GO
PRINT N'Dropping [auth].[SchoolIdToStudentUSI].[UCIX_SchoolIdToStudentUSI]...';


GO
DROP INDEX [UCIX_SchoolIdToStudentUSI]
    ON [auth].[SchoolIdToStudentUSI];


GO
PRINT N'Dropping [auth].[ParentUSIToStudentUSI].[UCIX_ParentUSIToStudentUSI]...';


GO
DROP INDEX [UCIX_ParentUSIToStudentUSI]
    ON [auth].[ParentUSIToStudentUSI];


GO
PRINT N'Altering [auth].[EducationOrganizationIdToEducationServiceCenterId]...';


GO
ALTER VIEW auth.EducationOrganizationIdToEducationServiceCenterId
AS
    SELECT DISTINCT EducationServiceCenterId
                  ,EdOrgId AS EducationOrganizationId
    FROM (
             SELECT *
             FROM auth.EducationOrganizationIdentifiers
         ) AS Source
-- Only LEAs and Schools are accessible to ESC-level claims
             UNPIVOT(EdOrgId FOR IdType IN (
            LocalEducationAgencyId
            ,SchoolId
            )) AS UnpivotedSource

    UNION

-- ESC-level claims also can access the ESC
    SELECT EducationServiceCenterId
         ,EducationServiceCenterId AS EducationOrganizationId
    FROM edfi.EducationServiceCenter;
GO
PRINT N'Altering [auth].[EducationOrganizationIdToStateAgencyId]...';


GO
ALTER VIEW auth.EducationOrganizationIdToStateAgencyId
AS
    SELECT DISTINCT StateEducationAgencyId
                  ,EdOrgId AS EducationOrganizationId
    FROM (
             SELECT *
             FROM auth.EducationOrganizationIdentifiers
         ) AS Source
             UNPIVOT(EdOrgId FOR IdType IN (
            EducationServiceCenterId
            ,LocalEducationAgencyId
            ,SchoolId
            )) -- Only ESCs, LEAs and Schools are accessible to State-level claims
             AS UnpivotedSource

    UNION

-- State-level claims also can access the State
    SELECT StateEducationAgencyId
         ,StateEducationAgencyId AS EducationOrganizationId
    FROM edfi.StateEducationAgency;
GO
PRINT N'Altering [auth].[EducationOrganizationToStaffUSI_Assignment]...';


GO
ALTER VIEW auth.EducationOrganizationToStaffUSI_Assignment
    WITH SCHEMABINDING
AS
-- EdOrg to Staff (through assignment)
SELECT edorg.EducationOrganizationId
     ,assgn.StaffUSI
     ,COUNT_BIG(*) AS Count
FROM edfi.EducationOrganization edorg
         INNER JOIN edfi.StaffEducationOrganizationAssignmentAssociation assgn ON
        edorg.EducationOrganizationId = assgn.EducationOrganizationId
GROUP BY assgn.StaffUSI
       ,edorg.EducationOrganizationId;
GO
PRINT N'Creating [auth].[EducationOrganizationToStaffUSI_Assignment].[UCIX_EducationOrganizationToStaffUSI_Assignment]...';


GO
CREATE UNIQUE CLUSTERED INDEX [UCIX_EducationOrganizationToStaffUSI_Assignment]
    ON [auth].[EducationOrganizationToStaffUSI_Assignment]([StaffUSI] ASC, [EducationOrganizationId] ASC);


GO
PRINT N'Altering [auth].[EducationOrganizationToStaffUSI_Employment]...';


GO
ALTER VIEW auth.EducationOrganizationToStaffUSI_Employment
    WITH SCHEMABINDING
AS
-- EdOrg to Staff (through Employment)
SELECT edorg.EducationOrganizationId
     ,empl.StaffUSI
     ,COUNT_BIG(*) AS Count
FROM edfi.EducationOrganization edorg
         INNER JOIN edfi.StaffEducationOrganizationEmploymentAssociation empl ON edorg.EducationOrganizationId = empl.EducationOrganizationId
GROUP BY empl.StaffUSI
       ,edorg.EducationOrganizationId;
GO
PRINT N'Creating [auth].[EducationOrganizationToStaffUSI_Employment].[UCIX_EducationOrganizationToStaffUSI_Employment]...';


GO
CREATE UNIQUE CLUSTERED INDEX [UCIX_EducationOrganizationToStaffUSI_Employment]
    ON [auth].[EducationOrganizationToStaffUSI_Employment]([StaffUSI] ASC, [EducationOrganizationId] ASC);


GO
PRINT N'Altering [auth].[LocalEducationAgencyIdToParentUSI]...';


GO
ALTER VIEW auth.LocalEducationAgencyIdToParentUSI
    WITH SCHEMABINDING
AS
-- LEA to Parent USI
SELECT sch.LocalEducationAgencyId
     ,spa.ParentUSI
     ,COUNT_BIG(*) AS Count
FROM edfi.School sch
         INNER JOIN edfi.StudentSchoolAssociation ssa ON
        sch.SchoolId = ssa.SchoolId
         INNER JOIN edfi.Student s ON
        ssa.StudentUSI = s.StudentUSI
         INNER JOIN edfi.StudentParentAssociation spa ON
        ssa.StudentUSI = spa.StudentUSI
GROUP BY spa.ParentUSI
       ,LocalEducationAgencyId;
GO
PRINT N'Creating [auth].[LocalEducationAgencyIdToParentUSI].[UCIX_LocalEducationAgencyIdToParentUSI]...';


GO
CREATE UNIQUE CLUSTERED INDEX [UCIX_LocalEducationAgencyIdToParentUSI]
    ON [auth].[LocalEducationAgencyIdToParentUSI]([ParentUSI] ASC, [LocalEducationAgencyId] ASC);


GO
PRINT N'Altering [auth].[LocalEducationAgencyIdToStudentUSI]...';


GO
ALTER VIEW auth.LocalEducationAgencyIdToStudentUSI
    WITH SCHEMABINDING
AS
-- LEA to Student GUID
SELECT sch.LocalEducationAgencyId
     ,ssa.StudentUSI
     ,COUNT_BIG(*) AS Ignored
FROM edfi.School sch
         INNER JOIN edfi.StudentSchoolAssociation ssa ON sch.SchoolId = ssa.SchoolId
GROUP BY sch.LocalEducationAgencyId
       ,ssa.StudentUSI;
GO
PRINT N'Creating [auth].[LocalEducationAgencyIdToStudentUSI].[UCIX_LocalEducationAgencyToStudentUSI]...';


GO
CREATE UNIQUE CLUSTERED INDEX [UCIX_LocalEducationAgencyToStudentUSI]
    ON [auth].[LocalEducationAgencyIdToStudentUSI]([StudentUSI] ASC, [LocalEducationAgencyId] ASC);


GO
PRINT N'Altering [auth].[LocalEducationAgencyIdToStudentUSIThroughEdOrgAssociation]...';


GO
ALTER VIEW auth.LocalEducationAgencyIdToStudentUSIThroughEdOrgAssociation
AS
    SELECT DISTINCT lea.LocalEducationAgencyId
         ,seoa_lea.StudentUSI
    FROM edfi.LocalEducationAgency lea
             INNER JOIN edfi.StudentEducationOrganizationAssociation seoa_lea ON
            lea.LocalEducationAgencyId = seoa_lea.EducationOrganizationId

    UNION

    SELECT DISTINCT sch.LocalEducationAgencyId
         ,seoa_sch.StudentUSI
    FROM edfi.School sch
             INNER JOIN edfi.StudentEducationOrganizationAssociation seoa_sch ON
            sch.SchoolId = seoa_sch.EducationOrganizationId;
GO
PRINT N'Altering [auth].[ParentUSIToSchoolId]...';


GO
ALTER VIEW auth.ParentUSIToSchoolId
    WITH SCHEMABINDING
AS
-- School to Parent USI
SELECT ssa.SchoolId
     ,spa.ParentUSI
     ,COUNT_BIG(*) AS Count
FROM edfi.StudentSchoolAssociation ssa
         INNER JOIN edfi.Student s ON
        ssa.StudentUSI = s.StudentUSI
         INNER JOIN edfi.StudentParentAssociation spa ON
        ssa.StudentUSI = spa.StudentUSI
GROUP BY spa.ParentUSI
       ,SchoolId;
GO
PRINT N'Creating [auth].[ParentUSIToSchoolId].[UCIX_ParentUSIToSchoolId]...';


GO
CREATE UNIQUE CLUSTERED INDEX [UCIX_ParentUSIToSchoolId]
    ON [auth].[ParentUSIToSchoolId]([ParentUSI] ASC, [SchoolId] ASC);


GO
PRINT N'Altering [auth].[ParentUSIToStudentUSI]...';


GO
ALTER VIEW auth.ParentUSIToStudentUSI
    WITH SCHEMABINDING
AS
SELECT spa.StudentUSI
     ,spa.ParentUSI
     ,COUNT_BIG(*) AS Count
FROM edfi.StudentParentAssociation spa
GROUP BY spa.StudentUSI
     ,spa.ParentUSI;
GO
PRINT N'Creating [auth].[ParentUSIToStudentUSI].[UCIX_ParentUSIToStudentUSI]...';


GO
CREATE UNIQUE CLUSTERED INDEX [UCIX_ParentUSIToStudentUSI]
    ON [auth].[ParentUSIToStudentUSI]([StudentUSI] ASC, [ParentUSI] ASC);


GO
PRINT N'Creating [auth].[ParentUSIToStudentUSI].[IX_ParentUSIToStudentUSI]...';


GO
CREATE NONCLUSTERED INDEX [IX_ParentUSIToStudentUSI]
    ON [auth].[ParentUSIToStudentUSI]([ParentUSI] ASC, [StudentUSI] ASC);


GO
PRINT N'Altering [auth].[SchoolIdToStaffUSI]...';


GO
ALTER VIEW auth.SchoolIdToStaffUSI
AS
-- School to Staff (through employment)
    SELECT DISTINCT sch.SchoolId
         ,seo_empl.StaffUSI
    FROM edfi.School sch
             INNER JOIN edfi.StaffEducationOrganizationEmploymentAssociation seo_empl ON
            sch.SchoolId = seo_empl.EducationOrganizationId

    UNION ALL

-- School to Staff (through assignment)
    SELECT DISTINCT sch.SchoolId
         ,seo_assgn.StaffUSI
    FROM edfi.School sch
             INNER JOIN edfi.StaffEducationOrganizationAssignmentAssociation seo_assgn ON
            sch.SchoolId = seo_assgn.EducationOrganizationId;
GO
PRINT N'Altering [auth].[SchoolIdToStudentUSI]...';


GO
ALTER VIEW auth.SchoolIdToStudentUSI
    WITH SCHEMABINDING
AS
-- LEA to Student GUID
SELECT ssa.SchoolId
     ,ssa.StudentUSI
     ,COUNT_BIG(*) AS Ignored
FROM edfi.StudentSchoolAssociation ssa
GROUP BY ssa.SchoolId
     ,ssa.StudentUSI;
GO
PRINT N'Creating [auth].[SchoolIdToStudentUSI].[UCIX_SchoolIdToStudentUSI]...';


GO
CREATE UNIQUE CLUSTERED INDEX [UCIX_SchoolIdToStudentUSI]
    ON [auth].[SchoolIdToStudentUSI]([StudentUSI] ASC, [SchoolId] ASC);


GO
PRINT N'Altering [auth].[SchoolIdToStudentUSIThroughEdOrgAssociation]...';


GO
ALTER VIEW auth.SchoolIdToStudentUSIThroughEdOrgAssociation
    WITH SCHEMABINDING
AS
SELECT DISTINCT SchoolId
     ,seoa.StudentUSI
FROM edfi.School sch
         INNER JOIN edfi.StudentEducationOrganizationAssociation seoa ON
        sch.SchoolId = seoa.EducationOrganizationId;
GO
PRINT N'Altering [auth].[EducationOrganizationIdToStudentUSI]...';


GO
ALTER VIEW auth.EducationOrganizationIdToStudentUSI
AS
    SELECT SchoolId As EducationOrganizationId, StudentUSI
    FROM auth.SchoolIdToStudentUSI

    UNION ALL
    SELECT LocalEducationAgencyId As EducationOrganizationId, StudentUSI
    FROM auth.LocalEducationAgencyIdToStudentUSI
GO
PRINT N'Altering [auth].[LocalEducationAgencyIdToStaffUSI]...';


GO
ALTER VIEW auth.LocalEducationAgencyIdToStaffUSI
AS
-- LEA to Staff (through employment)
    SELECT emp.EducationOrganizationId AS LocalEducationAgencyId
         ,NULL AS SchoolId
         ,emp.StaffUSI
    FROM edfi.LocalEducationAgency lea
             INNER JOIN auth.EducationOrganizationToStaffUSI_Employment emp ON
            lea.LocalEducationAgencyId = emp.EducationOrganizationId

    UNION ALL

-- LEA to Staff (through assignment)
    SELECT assgn.EducationOrganizationId AS LocalEducationAgencyId
         ,NULL AS SchoolId
         ,assgn.StaffUSI
    FROM edfi.LocalEducationAgency lea
             INNER JOIN auth.EducationOrganizationToStaffUSI_Assignment assgn ON
            lea.LocalEducationAgencyId = assgn.EducationOrganizationId

    UNION ALL

-- School to Staff (through employment)
    SELECT sch.LocalEducationAgencyId
         ,emp.EducationOrganizationId AS SchoolId
         ,emp.StaffUSI
    FROM edfi.School sch
             INNER JOIN auth.EducationOrganizationToStaffUSI_Employment emp ON
            sch.SchoolId = emp.EducationOrganizationId

    UNION ALL

-- School to Staff (through assignment)
    SELECT sch.LocalEducationAgencyId
         ,assgn.EducationOrganizationId AS SchoolId
         ,assgn.StaffUSI
    FROM edfi.School sch
             INNER JOIN auth.EducationOrganizationToStaffUSI_Assignment assgn ON
            sch.SchoolId = assgn.EducationOrganizationId;
GO
PRINT N'Altering [auth].[EducationOrganizationIdToStaffUSI]...';


GO
ALTER VIEW auth.EducationOrganizationIdToStaffUSI
AS
    SELECT SchoolId AS EducationOrganizationId
         ,StaffUSI
    FROM auth.SchoolIdToStaffUSI

    UNION ALL

    SELECT LocalEducationAgencyId AS EducationOrganizationId
         ,StaffUSI
    FROM auth.LocalEducationAgencyIdToStaffUSI;
GO
PRINT N'Update complete.';


GO
