// SPDX-License-Identifier: Apache-2.0
// Licensed to the Ed-Fi Alliance under one or more agreements.
// The Ed-Fi Alliance licenses this file to you under the Apache License, Version 2.0.
// See the LICENSE and NOTICES files in the project root for more information.

using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace EdFi.Ods.Common.Exceptions;

public interface IEdFiProblemDetails
{
    /// <summary>
    /// A human-readable explanation specific to this occurrence of the problem.
    /// </summary>
    [JsonPropertyName("detail")]
    string Detail { get; }

    /// <summary>
    /// A URI reference [RFC3986] that identifies the problem type. This specification encourages that, when
    /// dereferenced, it provide human-readable documentation for the problem type
    /// (e.g., using HTML [W3C.REC-html5-20141028]).  When this member is not present, its value is assumed to be
    /// "about:blank".
    /// </summary>
    [JsonPropertyName("type")]
    string Type { get; }

    /// <summary>
    /// A short, human-readable summary of the problem type.It SHOULD NOT change from occurrence to occurrence
    /// of the problem, except for purposes of localization(e.g., using proactive content negotiation;
    /// see[RFC7231], Section 3.4).
    /// </summary>
    [JsonPropertyName("title")]
    string Title { get; }

    /// <summary>
    /// The HTTP status code([RFC7231], Section 6) generated by the origin server for this occurrence of the problem.
    /// </summary>
    [JsonPropertyName("status")]
    int Status { get; }

    // For possible future support.
    // /// <summary>
    // /// A URI reference that identifies the specific occurrence of the problem. It may or may not yield further information if dereferenced.
    // /// </summary>
    // [DataMember(Name = "instance")]
    // public string Instance { get; set; }

    /// <summary>
    /// Gets or sets a correlation id that is logged with the details of the exception.
    /// </summary>
    [JsonPropertyName("correlationId")]
    string CorrelationId { get; set; }

    /// <summary>
    /// Contains arrays of validation errors keyed by JSON Path (intended for use by a domain expert).
    /// </summary>
    [JsonPropertyName("validationErrors")]
    Dictionary<string, string[]> ValidationErrors { get; set; }

    /// <summary>
    /// Contains an array of error messages encountered while processing the request (intended for use by a technical audience).
    /// </summary>
    [JsonPropertyName("errors")]
    string[] Errors { get; set; }
}
