-- SPDX-License-Identifier: Apache-2.0
-- Licensed to the Ed-Fi Alliance under one or more agreements.
-- The Ed-Fi Alliance licenses this file to you under the Apache License, Version 2.0.
-- See the LICENSE and NOTICES files in the project root for more information.

DROP TABLE IF EXISTS tracked_deletes_edfi.absenceeventcategorydescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.absenceeventcategorydescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.academichonorcategorydescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.academichonorcategorydescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.academicsubjectdescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.academicsubjectdescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.academicweek;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.academicweek_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.accommodationdescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.accommodationdescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.account;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.account_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.accountabilityrating;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.accountabilityrating_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.accountclassificationdescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.accountclassificationdescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.accountcode;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.accountcode_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.achievementcategorydescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.achievementcategorydescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.actual;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.actual_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.additionalcredittypedescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.additionalcredittypedescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.addresstypedescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.addresstypedescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.administrationenvironmentdescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.administrationenvironmentdescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.administrativefundingcontroldescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.administrativefundingcontroldescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.ancestryethnicorigindescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.ancestryethnicorigindescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.assessment;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.assessment_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.assessmentcategorydescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.assessmentcategorydescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.assessmentidentificationsystemdescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.assessmentidentificationsystemdescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.assessmentitem;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.assessmentitem_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.assessmentitemcategorydescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.assessmentitemcategorydescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.assessmentitemresultdescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.assessmentitemresultdescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.assessmentperioddescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.assessmentperioddescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.assessmentreportingmethoddescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.assessmentreportingmethoddescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.assessmentscorerangelearningstandard;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.assessmentscorerangelearningstandard_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.attemptstatusdescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.attemptstatusdescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.attendanceeventcategorydescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.attendanceeventcategorydescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.behaviordescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.behaviordescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.bellschedule;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.bellschedule_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.budget;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.budget_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.calendar;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.calendar_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.calendardate;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.calendardate_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.calendareventdescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.calendareventdescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.calendartypedescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.calendartypedescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.careerpathwaydescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.careerpathwaydescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.charterapprovalagencytypedescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.charterapprovalagencytypedescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.charterstatusdescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.charterstatusdescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.citizenshipstatusdescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.citizenshipstatusdescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.classperiod;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.classperiod_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.classroompositiondescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.classroompositiondescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.cohort;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.cohort_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.cohortscopedescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.cohortscopedescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.cohorttypedescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.cohorttypedescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.cohortyeartypedescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.cohortyeartypedescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.communityorganization;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.communityorganization_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.communityprovider;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.communityprovider_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.communityproviderlicense;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.communityproviderlicense_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.competencyleveldescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.competencyleveldescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.competencyobjective;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.competencyobjective_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.contacttypedescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.contacttypedescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.contentclassdescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.contentclassdescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.continuationofservicesreasondescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.continuationofservicesreasondescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.contractedstaff;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.contractedstaff_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.costratedescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.costratedescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.countrydescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.countrydescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.course;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.course_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.courseattemptresultdescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.courseattemptresultdescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.coursedefinedbydescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.coursedefinedbydescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.coursegpaapplicabilitydescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.coursegpaapplicabilitydescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.courseidentificationsystemdescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.courseidentificationsystemdescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.courselevelcharacteristicdescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.courselevelcharacteristicdescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.courseoffering;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.courseoffering_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.courserepeatcodedescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.courserepeatcodedescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.coursetranscript;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.coursetranscript_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.credential;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.credential_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.credentialfielddescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.credentialfielddescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.credentialtypedescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.credentialtypedescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.creditcategorydescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.creditcategorydescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.credittypedescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.credittypedescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.cteprogramservicedescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.cteprogramservicedescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.curriculumuseddescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.curriculumuseddescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.deliverymethoddescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.deliverymethoddescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.descriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.descriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.diagnosisdescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.diagnosisdescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.diplomaleveldescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.diplomaleveldescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.diplomatypedescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.diplomatypedescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.disabilitydescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.disabilitydescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.disabilitydesignationdescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.disabilitydesignationdescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.disabilitydeterminationsourcetypedescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.disabilitydeterminationsourcetypedescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.disciplineaction;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.disciplineaction_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.disciplineactionlengthdifferencereasondescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.disciplineactionlengthdifferencereasondescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.disciplinedescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.disciplinedescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.disciplineincident;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.disciplineincident_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.disciplineincidentparticipationcodedescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.disciplineincidentparticipationcodedescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.educationalenvironmentdescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.educationalenvironmentdescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.educationcontent;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.educationcontent_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.educationorganization;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.educationorganization_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.educationorganizationcategorydescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.educationorganizationcategorydescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.educationorganizationidentificationsystemdescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.educationorganizationidentificationsystemdescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.educationorganizationinterventionprescriptionassociation;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.educationorganizationinterventionprescription_e670ae_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.educationorganizationnetwork;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.educationorganizationnetwork_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.educationorganizationnetworkassociation;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.educationorganizationnetworkassociation_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.educationorganizationpeerassociation;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.educationorganizationpeerassociation_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.educationplandescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.educationplandescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.educationservicecenter;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.educationservicecenter_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.electronicmailtypedescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.electronicmailtypedescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.employmentstatusdescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.employmentstatusdescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.entrygradelevelreasondescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.entrygradelevelreasondescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.entrytypedescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.entrytypedescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.eventcircumstancedescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.eventcircumstancedescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.exitwithdrawtypedescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.exitwithdrawtypedescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.feederschoolassociation;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.feederschoolassociation_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.generalstudentprogramassociation;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.generalstudentprogramassociation_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.grade;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.grade_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.gradebookentry;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.gradebookentry_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.gradebookentrytypedescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.gradebookentrytypedescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.gradeleveldescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.gradeleveldescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.gradepointaveragetypedescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.gradepointaveragetypedescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.gradetypedescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.gradetypedescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.gradingperiod;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.gradingperiod_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.gradingperioddescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.gradingperioddescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.graduationplan;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.graduationplan_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.graduationplantypedescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.graduationplantypedescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.gunfreeschoolsactreportingstatusdescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.gunfreeschoolsactreportingstatusdescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.homelessprimarynighttimeresidencedescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.homelessprimarynighttimeresidencedescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.homelessprogramservicedescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.homelessprogramservicedescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.identificationdocumentusedescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.identificationdocumentusedescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.incidentlocationdescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.incidentlocationdescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.indicatordescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.indicatordescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.indicatorgroupdescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.indicatorgroupdescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.indicatorleveldescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.indicatorleveldescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.institutiontelephonenumbertypedescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.institutiontelephonenumbertypedescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.interactivitystyledescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.interactivitystyledescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.internetaccessdescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.internetaccessdescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.intervention;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.intervention_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.interventionclassdescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.interventionclassdescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.interventioneffectivenessratingdescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.interventioneffectivenessratingdescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.interventionprescription;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.interventionprescription_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.interventionstudy;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.interventionstudy_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.languagedescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.languagedescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.languageinstructionprogramservicedescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.languageinstructionprogramservicedescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.languageusedescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.languageusedescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.learningobjective;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.learningobjective_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.learningstandard;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.learningstandard_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.learningstandardcategorydescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.learningstandardcategorydescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.learningstandardequivalenceassociation;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.learningstandardequivalenceassociation_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.learningstandardequivalencestrengthdescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.learningstandardequivalencestrengthdescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.learningstandardscopedescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.learningstandardscopedescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.levelofeducationdescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.levelofeducationdescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.licensestatusdescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.licensestatusdescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.licensetypedescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.licensetypedescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.limitedenglishproficiencydescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.limitedenglishproficiencydescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.localedescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.localedescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.localeducationagency;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.localeducationagency_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.localeducationagencycategorydescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.localeducationagencycategorydescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.location;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.location_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.magnetspecialprogramemphasisschooldescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.magnetspecialprogramemphasisschooldescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.mediumofinstructiondescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.mediumofinstructiondescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.methodcreditearneddescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.methodcreditearneddescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.migranteducationprogramservicedescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.migranteducationprogramservicedescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.monitoreddescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.monitoreddescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.neglectedordelinquentprogramdescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.neglectedordelinquentprogramdescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.neglectedordelinquentprogramservicedescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.neglectedordelinquentprogramservicedescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.networkpurposedescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.networkpurposedescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.objectiveassessment;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.objectiveassessment_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.oldethnicitydescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.oldethnicitydescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.openstaffposition;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.openstaffposition_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.operationalstatusdescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.operationalstatusdescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.organizationdepartment;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.organizationdepartment_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.othernametypedescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.othernametypedescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.parent;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.parent_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.participationdescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.participationdescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.participationstatusdescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.participationstatusdescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.payroll;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.payroll_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.performancebaseconversiondescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.performancebaseconversiondescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.performanceleveldescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.performanceleveldescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.person;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.person_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.personalinformationverificationdescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.personalinformationverificationdescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.platformtypedescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.platformtypedescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.populationserveddescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.populationserveddescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.postingresultdescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.postingresultdescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.postsecondaryevent;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.postsecondaryevent_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.postsecondaryeventcategorydescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.postsecondaryeventcategorydescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.postsecondaryinstitution;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.postsecondaryinstitution_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.postsecondaryinstitutionleveldescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.postsecondaryinstitutionleveldescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.proficiencydescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.proficiencydescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.program;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.program_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.programassignmentdescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.programassignmentdescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.programcharacteristicdescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.programcharacteristicdescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.programsponsordescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.programsponsordescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.programtypedescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.programtypedescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.progressdescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.progressdescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.progressleveldescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.progressleveldescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.providercategorydescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.providercategorydescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.providerprofitabilitydescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.providerprofitabilitydescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.providerstatusdescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.providerstatusdescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.publicationstatusdescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.publicationstatusdescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.questionformdescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.questionformdescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.racedescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.racedescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.reasonexiteddescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.reasonexiteddescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.reasonnottesteddescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.reasonnottesteddescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.recognitiontypedescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.recognitiontypedescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.relationdescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.relationdescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.repeatidentifierdescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.repeatidentifierdescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.reportcard;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.reportcard_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.reporterdescriptiondescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.reporterdescriptiondescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.residencystatusdescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.residencystatusdescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.responseindicatordescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.responseindicatordescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.responsibilitydescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.responsibilitydescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.restraintevent;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.restraintevent_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.restrainteventreasondescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.restrainteventreasondescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.resultdatatypetypedescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.resultdatatypetypedescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.retestindicatordescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.retestindicatordescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.school;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.school_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.schoolcategorydescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.schoolcategorydescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.schoolchoiceimplementstatusdescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.schoolchoiceimplementstatusdescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.schoolfoodserviceprogramservicedescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.schoolfoodserviceprogramservicedescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.schooltypedescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.schooltypedescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.schoolyeartype;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.schoolyeartype_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.section;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.section_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.sectionattendancetakenevent;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.sectionattendancetakenevent_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.sectioncharacteristicdescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.sectioncharacteristicdescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.separationdescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.separationdescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.separationreasondescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.separationreasondescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.servicedescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.servicedescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.session;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.session_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.sexdescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.sexdescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.sourcesystemdescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.sourcesystemdescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.specialeducationprogramservicedescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.specialeducationprogramservicedescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.specialeducationsettingdescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.specialeducationsettingdescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.staff;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.staff_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.staffabsenceevent;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.staffabsenceevent_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.staffclassificationdescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.staffclassificationdescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.staffcohortassociation;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.staffcohortassociation_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.staffdisciplineincidentassociation;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.staffdisciplineincidentassociation_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.staffeducationorganizationassignmentassociation;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.staffeducationorganizationassignmentassociation_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.staffeducationorganizationcontactassociation;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.staffeducationorganizationcontactassociation_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.staffeducationorganizationemploymentassociation;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.staffeducationorganizationemploymentassociation_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.staffidentificationsystemdescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.staffidentificationsystemdescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.staffleave;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.staffleave_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.staffleaveeventcategorydescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.staffleaveeventcategorydescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.staffprogramassociation;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.staffprogramassociation_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.staffschoolassociation;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.staffschoolassociation_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.staffsectionassociation;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.staffsectionassociation_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.stateabbreviationdescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.stateabbreviationdescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.stateeducationagency;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.stateeducationagency_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.student;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.student_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.studentacademicrecord;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.studentacademicrecord_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.studentassessment;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.studentassessment_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.studentcharacteristicdescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.studentcharacteristicdescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.studentcohortassociation;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.studentcohortassociation_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.studentcompetencyobjective;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.studentcompetencyobjective_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.studentcteprogramassociation;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.studentcteprogramassociation_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.studentdisciplineincidentassociation;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.studentdisciplineincidentassociation_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.studentdisciplineincidentbehaviorassociation;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.studentdisciplineincidentbehaviorassociation_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.studentdisciplineincidentnonoffenderassociation;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.studentdisciplineincidentnonoffenderassociation_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.studenteducationorganizationassociation;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.studenteducationorganizationassociation_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.studenteducationorganizationresponsibilityassociation;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.studenteducationorganizationresponsibilityass_42aa64_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.studentgradebookentry;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.studentgradebookentry_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.studenthomelessprogramassociation;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.studenthomelessprogramassociation_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.studentidentificationsystemdescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.studentidentificationsystemdescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.studentinterventionassociation;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.studentinterventionassociation_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.studentinterventionattendanceevent;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.studentinterventionattendanceevent_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.studentlanguageinstructionprogramassociation;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.studentlanguageinstructionprogramassociation_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.studentlearningobjective;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.studentlearningobjective_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.studentmigranteducationprogramassociation;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.studentmigranteducationprogramassociation_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.studentneglectedordelinquentprogramassociation;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.studentneglectedordelinquentprogramassociation_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.studentparentassociation;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.studentparentassociation_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.studentparticipationcodedescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.studentparticipationcodedescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.studentprogramassociation;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.studentprogramassociation_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.studentprogramattendanceevent;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.studentprogramattendanceevent_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.studentschoolassociation;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.studentschoolassociation_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.studentschoolattendanceevent;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.studentschoolattendanceevent_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.studentschoolfoodserviceprogramassociation;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.studentschoolfoodserviceprogramassociation_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.studentsectionassociation;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.studentsectionassociation_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.studentsectionattendanceevent;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.studentsectionattendanceevent_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.studentspecialeducationprogramassociation;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.studentspecialeducationprogramassociation_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.studenttitleipartaprogramassociation;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.studenttitleipartaprogramassociation_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.survey;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.survey_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.surveycategorydescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.surveycategorydescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.surveycourseassociation;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.surveycourseassociation_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.surveyleveldescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.surveyleveldescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.surveyprogramassociation;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.surveyprogramassociation_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.surveyquestion;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.surveyquestion_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.surveyquestionresponse;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.surveyquestionresponse_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.surveyresponse;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.surveyresponse_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.surveyresponseeducationorganizationtargetassociation;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.surveyresponseeducationorganizationtargetassociation_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.surveyresponsestafftargetassociation;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.surveyresponsestafftargetassociation_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.surveysection;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.surveysection_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.surveysectionassociation;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.surveysectionassociation_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.surveysectionresponse;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.surveysectionresponse_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.surveysectionresponseeducationorganizationtargetassociation;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.surveysectionresponseeducationorganizationtar_730be1_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.surveysectionresponsestafftargetassociation;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.surveysectionresponsestafftargetassociation_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.teachingcredentialbasisdescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.teachingcredentialbasisdescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.teachingcredentialdescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.teachingcredentialdescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.technicalskillsassessmentdescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.technicalskillsassessmentdescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.telephonenumbertypedescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.telephonenumbertypedescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.termdescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.termdescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.titleipartaparticipantdescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.titleipartaparticipantdescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.titleipartaprogramservicedescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.titleipartaprogramservicedescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.titleipartaschooldesignationdescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.titleipartaschooldesignationdescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.tribalaffiliationdescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.tribalaffiliationdescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.visadescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.visadescriptor_tr_deltrkg() CASCADE;
DROP TABLE IF EXISTS tracked_deletes_edfi.weapondescriptor;
DROP FUNCTION IF EXISTS tracked_deletes_edfi.weapondescriptor_tr_deltrkg() CASCADE;
