name: EdFi.Ods.Common Pull request build and test

on:
  pull_request:
    branches: [main]

env:
  INFORMATIONAL_VERSION: "5.4"
  CONFIGURATION: "Release"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2
    - name: Setup .NET
      uses: actions/setup-dotnet@9211491ffb35dd6a6657ca4f45d43dfe6e97c829 # v2
      with:
        dotnet-version: 6.0.x
    - name: build
      run: |
        .\build.ps1 build -Configuration ${{ env.CONFIGURATION }} -InformationalVersion ${{ env.INFORMATIONAL_VERSION}} -BuildCounter ${{ github.run_number }} -ProjectFile "Application/EdFi.Ods.Common/EdFi.Ods.Common.csproj"
      shell: pwsh
    - name: test
      run: |
        .\build.ps1 test -Configuration ${{ env.CONFIGURATION }} -ProjectFile "Application/EdFi.Ods.Common/EdFi.Ods.Common.csproj"
      shell: pwsh
