# SPDX-License-Identifier: Apache-2.0
# Licensed to the Ed-Fi Alliance under one or more agreements.
# The Ed-Fi Alliance licenses this file to you under the Apache License, Version 2.0.
# See the LICENSE and NOTICES files in the project root for more information.

name: Packages - EdFi.Ods.Minimal.Template

on:
  pull_request:
    branches: [main]
  push:
    branches:
      - main
  workflow_dispatch:

env:
  EDFI_STANDARD_REFERENCE: "4.0.0-a"
  INFORMATIONAL_VERSION: "6.1"
  BUILD_INCREMENTER: "47"
  AZURE_ARTIFACT_URL: "https://pkgs.dev.azure.com/ed-fi-alliance/Ed-Fi-Alliance-OSS/_packaging/EdFi/nuget/v3/index.json"
  AZURE_ARTIFACT_NUGET_KEY: ${{ secrets.AZURE_ARTIFACTS_PERSONAL_ACCESS_TOKEN }}
  VSS_NUGET_EXTERNAL_FEED_ENDPOINTS : '{"endpointCredentials": [{"endpoint": "https://pkgs.dev.azure.com/ed-fi-alliance/Ed-Fi-Alliance-OSS/_packaging/EdFi/nuget/v3/index.json","password": "${{ secrets.AZURE_ARTIFACTS_PERSONAL_ACCESS_TOKEN }}"}]}'
  CONFIGURATION: "Release"
  EVENT:  ${{ GITHUB.EVENT }}
  HEAD_REF:  ${{ GITHUB.HEAD_REF }}
  REF_NAME:  ${{ GITHUB.REF_NAME }}

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Is pull request branch exists in Ed-Fi-ODS-Implementation
      working-directory: ./Ed-Fi-ODS-Implementation/
      shell: powershell
      run: |
           $current_branch = ''
           if (env.EVENT == 'push'){
            $current_branch = '${{env.REF_NAME}}''
           }
           else if (env.EVENT == 'pull_request'){
            $current_branch = '${{env.HEAD_REF}}''
           }
           else if (env.EVENT == 'workflow_dispatch'){
            $current_branch = '${{env.REF_NAME}}''
           }

           Write-Host "Current Branch: $current_branch"

           $patternName = 'refs/heads/' +  $current_branch
           $is_pull_request_branch = 'False'
           $is_pull_request_branch = git ls-remote --heads origin $current_branch | Select-String -Pattern $patternName -SimpleMatch -Quiet
           $odsBranch = '${{ env.ODS_CURRENT_BRANCH }}'
           if($odsBranch -ne ''){
              git fetch origin $odsBranch
              git checkout $odsBranch
           } else {
              if ($is_pull_request_branch -eq $true) {
                git fetch origin $current_branch
                git checkout $current_branch
              }
           }
    