# SPDX-License-Identifier: Apache-2.0
# Licensed to the Ed-Fi Alliance under one or more agreements.
# The Ed-Fi Alliance licenses this file to you under the Apache License, Version 2.0.
# See the LICENSE and NOTICES files in the project root for more information.

name: Pkg EdFi.Ods.Minimal.Template

on:
  pull_request:
    branches: [main, 'b-v*-patch*','feature-*']
  push:
    branches: ['b-v*-patch*','feature-*']
  workflow_dispatch:
    inputs:
      distinct_id:
        description: 'distinct ID for Rebuild Database Templates workflow'
        required: false
        default: 'distinct_id'

permissions: read-all

env:
  INFORMATIONAL_VERSION: "7.3"
  BUILD_INCREMENTER: "-923"
  AZURE_ARTIFACT_URL: "https://pkgs.dev.azure.com/ed-fi-alliance/Ed-Fi-Alliance-OSS/_packaging/EdFi/nuget/v3/index.json"
  AZURE_ARTIFACT_NUGET_KEY: ${{ secrets.AZURE_ARTIFACTS_PERSONAL_ACCESS_TOKEN }}
  VSS_NUGET_EXTERNAL_FEED_ENDPOINTS : '{"endpointCredentials": [{"endpoint": "https://pkgs.dev.azure.com/ed-fi-alliance/Ed-Fi-Alliance-OSS/_packaging/EdFi/nuget/v3/index.json","password": "${{ secrets.AZURE_ARTIFACTS_PERSONAL_ACCESS_TOKEN }}"}]}'
  CONFIGURATION: "Release"
  REPOSITORY_DISPATCH_BRANCH: ${{ github.event.client_payload.branch }}
  HEAD_REF:  ${{ GITHUB.HEAD_REF }}
  REF_NAME:  ${{ GITHUB.REF_NAME }}
  REPOSITORY_OWNER: ${{ GITHUB.REPOSITORY_OWNER }}

jobs:

  FindStandardAndExtensionVersions:
    uses: ./.github/workflows/Find Standard and Extension Versions.yml
    with:
      calling_branch: ${{ github.head_ref || github.ref_name }}

  build:
    if: ${{ always() }}
    needs: FindStandardAndExtensionVersions
    runs-on: ubuntu-latest

    strategy:
      matrix:
        StandardVersion: ${{ fromJson(needs.FindStandardAndExtensionVersions.outputs.StandardVersions) }}
        ExtensionVersion: ${{ fromJson(needs.FindStandardAndExtensionVersions.outputs.ExtensionVersions) }}
    name: build (Standard Version ${{ matrix.StandardVersion }})
    steps:
    - name: echo distinct ID ${{ github.event.inputs.distinct_id }}
      run:  echo "${{ github.event.inputs.distinct_id }}"      
    - name: Check for Azure token
      if: ${{ env.REPOSITORY_OWNER == 'Ed-Fi-Alliance-OSS' && env.AZURE_ARTIFACT_NUGET_KEY == '' }}
      run: | 
        echo "::error::Missing Azure Token"
        exit 1 
    - name: Checkout Ed-Fi-ODS
      uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
      with:
          repository: Ed-Fi-Alliance-OSS/Ed-Fi-ODS
          path: Ed-Fi-ODS/
    - name: Checkout Ed-Fi-ODS-Implementation
      uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
      with:
          repository: Ed-Fi-Alliance-OSS/Ed-Fi-ODS-Implementation
          path: Ed-Fi-ODS-Implementation/
    - name: Set Ed-Fi-Standard Reference
      working-directory: ./Ed-Fi-ODS/
      run: |
        $standardTag = .\build.githubactions.ps1 StandardTag -standardVersion ${{ matrix.StandardVersion }} -ProjectFile "./Application/EdFi.Ods.Standard/EdFi.Ods.Standard.csproj"
        echo "EDFI_STANDARD_REFERENCE=$standardTag">> $env:GITHUB_ENV
        Write-host "Ed-Fi-Standard Tag is  $standardTag"
      shell: pwsh
    - name: Checkout Ed-Fi-Data-Standard
      uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
      with:
          repository: Ed-Fi-Alliance-OSS/Ed-Fi-Data-Standard
          path: Ed-Fi-Data-Standard/
          ref: ${{ env.EDFI_STANDARD_REFERENCE }}
    - name: Is pull request branch exists in Ed-Fi-ODS-Implementation
      working-directory: ./Ed-Fi-ODS/
      shell: pwsh
      run: |
        .\build.githubactions.ps1 CheckoutBranch -RelativeRepoPath "../Ed-Fi-ODS-Implementation"
    - name: Start SQL Server (Linux)
      if: runner.os == 'Linux'              
      shell: bash         
      run: |
        # Generate a random password for SA and mask it in logs
        sa_pw=$(uuidgen) 
        echo "::add-mask::$sa_pw"

        echo "Starting SQL Server in a Docker container..."
        docker run -e "ACCEPT_EULA=Y" \
                  -e "SA_PASSWORD=$sa_pw" \
                  -e "MSSQL_PID=Developer" \
                  -e "MSSQL_COLLATION=SQL_Latin1_General_CP1_CS_AS" \
                  -e "INSTANCEID=MSSQLSERVER" \
                  -e "INSTANCENAME=MSSQLSERVER" \
                  -e "TCPENABLED=1" \
                  -e "UPDATEENABLED=FALSE" \
                  -e "FEATURES=SQL,Tools" \                  
                  -p 1433:1433 \
                  --name sqlserver \
                  -d mcr.microsoft.com/mssql/server:2019-latest
        
        # Set environment variables for sqlcmd
        echo "Setting environment variables for sqlcmd..."
        echo "SQLCMDPASSWORD=$sa_pw" >> $GITHUB_ENV
        echo "SQLCMDUSER=sa" >> $GITHUB_ENV
        echo "SQLCMDSERVER=localhost,1433" >> $GITHUB_ENV

        # Set connection string environment variable
        echo "Setting environment variable SQL_SERVER_CONNECTION_STRING to SQL connection string..."
        echo "SQL_SERVER_CONNECTION_STRING=Server=localhost;Database=master;User Id=sa;Password=$sa_pw;Encrypt=false;" >> $GITHUB_ENV
  
    - name: Setup server
      shell: pwsh
      run: |
        # Wait for availability then create initial catalog

        for ($i = 1; $i -le 30; $i++) {
          Write-Output "Attempt $i/30 to connect to SQL Server..."
          sqlcmd -b -Q "SELECT @@SERVERNAME as ServerName" 2>&1>$null
          if ($?) {
            Write-Output "  - SQL Server is now ready"
            break
          } else {
            Write-Output "  - Not ready, sleeping for 5s"
            Start-Sleep -seconds 5
          }
        }

        Write-Output "Creating initial catalog 'nservicebus'"
        sqlcmd -Q "CREATE DATABASE [nservicebus]"
    - name: update BUILD_INCREMENTER 
      run: |      
            $newRevision = ([int]${{ github.run_number }}) + ([int]${{env.BUILD_INCREMENTER}})
            if ($newRevision -lt 0) {
                $newRevision = 1
                echo "BUILD_INCREMENTER=$newRevision">> $env:GITHUB_ENV
            }
      shell: pwsh
    - name: Cache Nuget packages
      uses: actions/cache@58c146cc91c5b9e778e71775dfe9bf1442ad9a12 #v3.2.3
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj*', '**/configuration.packages.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget-
    - name: Restore NuGet packages
      working-directory: ./Ed-Fi-ODS/
      run: |
        .\build.githubactions.ps1 restore -Solution "$env:GITHUB_WORKSPACE/Ed-Fi-ODS-Implementation/Application/Ed-Fi-Ods.sln"
      shell: pwsh                
    - name: Initialize-DevelopmentEnvironment
      working-directory: ./Ed-Fi-ODS-Implementation/
      run: |
        $ErrorActionPreference = 'Stop'
        [Environment]::SetEnvironmentVariable('msbuild_buildConfiguration', '${{ env.CONFIGURATION }}')
        $PSVersionTable
          . $env:GITHUB_WORKSPACE/Ed-Fi-ODS-Implementation/Initialize-PowershellForDevelopment.ps1
        Initialize-DevelopmentEnvironment  -NoDeploy -NoRestore -StandardVersion ${{ matrix.StandardVersion }} -ExtensionVersion ${{ matrix.ExtensionVersion }}
      shell: pwsh
    - name: Remove Plug-Ins
      working-directory: ./Ed-Fi-ODS-Implementation/
      run: |
        $ErrorActionPreference = 'Stop'
        rm -R "./Plugin/Extensions.*"
      shell: pwsh 
    - name: Create Database Template (no extensions)
      working-directory: ./
      run: |
        $ErrorActionPreference = 'Stop'
        [Environment]::SetEnvironmentVariable('msbuild_buildConfiguration', '${{ env.CONFIGURATION }}')
        Import-Module -Force -Scope Global "$env:GITHUB_WORKSPACE/Ed-Fi-ODS-Implementation/DatabaseTemplate/Modules/create-minimal-template.psm1"
        Initialize-MinimalTemplate -samplePath './Ed-Fi-Data-Standard/Descriptors' -noExtensions -StandardVersion ${{ matrix.StandardVersion }}  -ExtensionVersion ${{ matrix.ExtensionVersion }}
      shell: pwsh
    - name: pack
      working-directory: ./Ed-Fi-ODS/
      run: |
        .\build.githubactions.ps1 pack -Configuration ${{ env.CONFIGURATION }} -InformationalVersion ${{ env.INFORMATIONAL_VERSION }} -BuildCounter ${{ github.run_number }} -BuildIncrementer ${{env.BUILD_INCREMENTER}} -NuspecFilePath "$env:GITHUB_WORKSPACE/Ed-Fi-ODS-Implementation/DatabaseTemplate/Database/EdFi.Ods.Minimal.Template.Standard.${{ matrix.StandardVersion }}.nuspec" -PackageName  "EdFi.Suite3.Ods.Minimal.Template.Standard.${{ matrix.StandardVersion }}" 
      shell: pwsh
    - name: Install-credential-handler
      if: ${{ env.AZURE_ARTIFACT_NUGET_KEY != '' &&  github.event_name == 'workflow_dispatch' }}
      working-directory: ./Ed-Fi-ODS-Implementation/
      run: |
         Import-Module -Force -Scope Global "$env:GITHUB_WORKSPACE/Ed-Fi-ODS-Implementation/logistics/scripts/modules/utility/cross-platform.psm1"
         if (Get-IsWindows -and -not Get-InstalledModule | Where-Object -Property Name -eq "7Zip4pwsh") {
              Install-Module -Force -Scope CurrentUser -Name 7Zip4pwsh
         }

          # using WebClient is faster then Invoke-WebRequest but shows no progress
          $sourceUrl = ' https://github.com/microsoft/artifacts-credprovider/releases/download/v1.0.0/Microsoft.NuGet.CredentialProvider.zip'
          $fileName = 'Microsoft.NuGet.CredentialProvider.zip'
          Write-host "Downloading file from $sourceUrl..."
          $webClient = New-Object System.Net.WebClient
          $webClient.DownloadFile($sourceUrl, "$env:temp/$fileName")

          Write-host "Download complete." 

          if (-not (Test-Path "$env:temp/$fileName")) {
              Write-Warning "Microsoft.NuGet.CredentialProvider file '$fileName' not found."
              exit 0
          }

          $packageFolder = "$env:temp/Microsoft.NuGet.CredentialProvider/"

          if ($fileName.EndsWith('.zip')) {
              Write-host "Extracting $fileName..."
              $zipFilePath = "$env:temp/$fileName"
              if (Test-Path $zipFilePath) { Expand-Archive -Force -Path $zipFilePath -DestinationPath $packageFolder }
              Copy-Item -Path $packageFolder\* -Destination "$env:UserProfile/.nuget/" -Recurse -Force
              Write-Host "Extracted to: $env:UserProfile\.nuget\plugins\" -ForegroundColor Green
          }
      shell: pwsh
    - name: publish 
      working-directory: ./Ed-Fi-ODS/
      if: ${{ env.AZURE_ARTIFACT_NUGET_KEY != '' &&  github.event_name == 'workflow_dispatch' }}
      run: |
        .\build.githubactions.ps1 publish -InformationalVersion ${{ env.INFORMATIONAL_VERSION }} -BuildCounter ${{ github.run_number }} -BuildIncrementer ${{env.BUILD_INCREMENTER}} -NuGetApiKey ${{ env.AZURE_ARTIFACT_NUGET_KEY }} -EdFiNuGetFeed ${{env.AZURE_ARTIFACT_URL}} -PackageName  "EdFi.Suite3.Ods.Minimal.Template.Standard.${{ matrix.StandardVersion }}"
      shell: pwsh      
    - name: Upload EdFi.Ods.Minimal.Template Artifacts
      if: success() || failure()
      uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8 # v3.1.0
      with:
        name: NugetPackages.Artifacts
        path: ${{ github.workspace }}/Ed-Fi-ODS/NugetPackages/EdFi.Suite3.Ods.Minimal.Template.*.nupkg
    - name: Move Log Files
      run: |
        $bulkLoadClientSourcePath = "${{ github.workspace }}/Ed-Fi-ODS/Utilities/DataLoading/EdFi.BulkLoadClient.Console/bin/${{ env.CONFIGURATION }}/net8.0/logfile.txt"
        $testHarnessSourcePath = "${{ github.workspace }}/Ed-Fi-ODS-Implementation/Application/EdFi.Ods.Api.IntegrationTestHarness/bin/${{ env.CONFIGURATION }}/net8.0/TestHarnessLog.log"
        $testHarnessRequestResponseDetailsSourcePath = "${{ github.workspace }}/Ed-Fi-ODS-Implementation/Application/EdFi.Ods.Api.IntegrationTestHarness/bin/${{ env.CONFIGURATION }}/net8.0/TestHarnessRequestResponseDetailsLog.log"        
        $destinationPath = "${{ github.workspace }}/CreateDatabaseTemplateLogs/"
        # Create the destination folder if it doesn't exist
        if (!(Test-Path -Path $destinationPath)) {
            New-Item -ItemType Directory -Path $destinationPath -Force
        }
        # Move the files
        Move-Item -Path $bulkLoadClientSourcePath -Destination $destinationPath -Force
        Move-Item -Path $testHarnessSourcePath -Destination $destinationPath -Force
        Move-Item -Path $testHarnessRequestResponseDetailsSourcePath -Destination $destinationPath -Force           
      shell: pwsh        
    - name: Upload Create Database Template Logs
      if: success() || failure()
      uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8 # v3.1.0
      with:
        name: Create Database Template Logs
        path: |
          ${{ github.workspace }}/CreateDatabaseTemplateLogs/*.* 